/**
 * DPO report handler (v2)
 *
 * Generates a markdown GDPR/DPO compliance report.
 * No external dependencies.
 */

import { z } from 'zod';
import { BaseHandler, type HandlerResult, type ActionContext } from './base.js';

export class DpoHandler extends BaseHandler {
  static type = 'dpo_report';
  static configSchema = z.object({
    organization: z.string().optional(),
    enabled: z.boolean().optional(),
  });

  readonly name = 'DPO Report';
  readonly type = 'dpo_report';

  private organization = 'PipeliNostr';

  async initialize(config: Record<string, unknown>): Promise<void> {
    if (config.organization) this.organization = config.organization as string;
  }

  async execute(action: Record<string, unknown>, context: ActionContext): Promise<HandlerResult> {
    const now = new Date();
    const date = now.toISOString().split('T')[0];
    const requester = (action.requester as string)
      ?? (context.trigger.sender as string)
      ?? 'unknown';

    const categories = (action.categories as string[]) ?? [
      'Nostr public key (npub)',
      'Event content (messages)',
      'Zap amounts (Lightning invoices)',
      'Relay connection metadata',
    ];

    const report = [
      `# DPO Compliance Report`,
      ``,
      `**Organization:** ${this.organization}`,
      `**Date:** ${date}`,
      `**Requester:** ${requester}`,
      ``,
      `## Data Categories Processed`,
      ``,
      ...categories.map(c => `- ${c}`),
      ``,
      `## Processing Summary`,
      ``,
      `| Aspect | Detail |`,
      `|--------|--------|`,
      `| Legal basis | Legitimate interest (Nostr event routing) |`,
      `| Data retention | Per workflow configuration |`,
      `| Third-party sharing | Only via configured outbound handlers |`,
      `| Encryption | NIP-04/NIP-44 for DMs, TLS for external APIs |`,
      `| Subject rights | Contact DPO via Nostr DM |`,
      ``,
      `## Actions`,
      ``,
      `- Data subject may request deletion via Nostr DM`,
      `- All processed events are transient unless stored by a workflow`,
      ``,
      `---`,
      `*Generated by PipeliNostr DPO handler on ${now.toISOString()}*`,
    ].join('\n');

    return {
      success: true,
      data: {
        report,
        date,
        requester,
        categories,
      },
    };
  }

  async shutdown(): Promise<void> {}
}
